"""Добавлены комментарии, чаты, сообщения

Revision ID: 2ac71573683d
Revises: 3fc77a3581ae
Create Date: 2020-05-11 21:00:16.564640

"""

# revision identifiers, used by Alembic.
revision = '2ac71573683d'
down_revision = '3fc77a3581ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
