"""Удаление ненужных полей

Revision ID: c2bc675f31ed
Revises: 2ac71573683d
Create Date: 2020-05-12 18:22:59.567178

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c2bc675f31ed'
down_revision = '2ac71573683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'achievements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('achievements', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
